### ISSUE TITLE
job delivered event only works half the time

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [kniffen/TruckSim-Telemetry#13]
`job.on("delivered")` events seems to only works half the time for me, for example:

1st Job -> `delivered` event emitted
2nd Job -> `delivered` event not emitted
3rd Job -> `delivered` event emitted
4th Job -> `delivered` event not emitted
5th Job -> `delivered` event emitted
... and so on

Upon investigation, it seems like this is caused by `events.job.delivered.active` is not being set with the proper value, it's supposed to be `false` when a job isn't delivered, instead the `events.job.delivered.active` value seems to be like this:

When taking 1st job -> `delivered.active` = `false`
When finished 1st job -> `delivered.active` is set to `true` and emits `delivered` event
When taking 2nd job -> `delivered.active` is still true and isn't set back to `false`
When finished 2nd job -> `delivered` event isn't emitted because `delivered.active` is `true`, then `delivered.active`  being set to `false`
and 3rd job behaves like when 1st job, and so on

**Comment by kniffen** [comment]
Hi, sorry for the late reply.

Can you try setting the interval option on the watch function to 16ms?
By default it's set to 100ms, meaning it checks the game for changes every 100ms and those events are some times active for less than that.
In a future update this will be changed to match the game.

~16ms should match the game's framerate (60 FPS)

```JS
const tst = require("trucksim-telemetry")

const telemetry = tst()

telemetry.job.on("delivered", function(data) {
  // use data
})

telemetry.watch({interval: 16})

```

**Comment by kniffen** [comment]
Upon farther testing it seems that this is an issue with the plugin itself.
I have submitted an issue there about it.
https://github.com/RenCloud/scs-sdk-plugin/issues/98

**Comment by kniffen** [comment]
Behaviour confirmed to be intentional.
Will try to look into updating the module for it later this week.
https://github.com/RenCloud/scs-sdk-plugin/issues/98#issuecomment-1047065111

**Comment by kniffen** [comment]
This issue should now be resolved
Part from the `refuel-paid` event, there seems to be an issue with the plugin for that one
https://github.com/kniffen/TruckSim-Telemetry/commit/509c14622c3a376d341d0ba91c1d4bc48f9bb842
