### ISSUE TITLE
Using RenCloud's fork for newer SDK versions

### ISSUE THREAD

**Issue by Tim3Game** [kniffen/TruckSim-Telemetry#2]
Hello,

I wanted to ask, if you could start using [RenCloud's scs-sdk-plugin fork](https://github.com/RenCloud/scs-sdk-plugin) for making use of never SDK versions. From what I looked up, it's the only fork of [nlhans's original depository](https://github.com/nlhans/ets2-sdk-plugin) that support's 1.9 SDK (and from what I read on his Discord server, he plans for updating it for the[ upcoming 1.10 SDK version](https://modding.scssoft.com/wiki/Documentation/Engine/SDK/Telemetry/Changelog)). I would love to update it myself and put it as a Pull request, but I have no C++ knowledge and would most likely broke it.

Thanks for any answer,
Tim3Game

**Comment by kniffen** [comment]
Interesting, i'll have to look into this.
Unknown when i'll get time though, so don't expect it to be implemented anytime soon.

**Comment by Tim3Game** [comment]
Thanks for your interest in implementing it.

**Comment by YeapGuy** [comment]
I agree. We need support for RenCloud's fork. It supports the latest 1.10 SDK.

**Comment by BeerGrizzly** [comment]
Yeah 1.35 events/cargo damage support would be great.

**Comment by kniffen** [comment]
Currently working on an update to support RenCloud's fork, but it's taking a bit longer than anticipated.
The update will hopefully be done by next week.

**Comment by kniffen** [comment]
The module is now updated to support rev.9 of [RenCloud](https://github.com/RenCloud/scs-sdk-plugin)'s plugin, will work on supporting rev.10 next
It's quite a big change so check [README.md](https://github.com/kniffen/TruckSim-Telemetry/blob/master/README.md) for new usage methods.

**Comment by YeapGuy** [comment]
Great, thank you @kniffen. I'm waiting for 1.10 :)

**Comment by kniffen** [comment]
Basic SDK 1.10 support complete, will add more events soon.
