### ISSUE TITLE
Fuel consumed, and timeTaken

### ISSUE THREAD

**Issue by velesco** [kniffen/TruckSim-Telemetry#23]
where can I find Fuel consumed, and timeTaken, and if not are you planning to add them?

**Comment by DevKilioZOfficiel** [comment]
It already exists for fuel consumption.

All you have to do is :

```
apiSdk.truck.fuel.value - apiSdk.truck.fuel.capacity

```

I use the “tst.getData()” api for this.

**Comment by velesco** [comment]
is there any function to appear in job delivery, for fuel consumption and time taken?

**Comment by DevKilioZOfficiel** [comment]
I don't know about that, I'm using the “Jobs” function, so let's see if I can find it.

**Comment by velesco** [comment]
sure, thank u

**Comment by kniffen** [comment]
The job delivered event has a `timeTaken` value
https://tst.kniffen.dev/#/events?id=delivered

For fuel you need to keep track of this yourself by comparing the truck's fuel before and after the delivery, and also take into consideration fuel stops along the way.
